// <auto-generated />
using System;
using CisApi.Infrastructure.MySQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CisApi.Infrastructure.MySQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006204930_CreateTopicsIdeas")]
    partial class CreateTopicsIdeas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.IdeaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("topic_id");

                    b.Property<long>("VoteCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vote_count");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("idx_ideas_topic");

                    b.ToTable("ideas", (string)null);
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.IdeaVotesEntity", b =>
                {
                    b.Property<int>("IdeaId")
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("voted_at");

                    b.HasKey("IdeaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("idea_votes", (string)null);
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.TopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("login");

                    b.HasKey("Id");

                    b.ToTable("users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.IdeaEntity", b =>
                {
                    b.HasOne("CisApi.Infrastructure.MySQL.Entities.UserEntity", "CreatedBy")
                        .WithMany("IdeasCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CisApi.Infrastructure.MySQL.Entities.TopicEntity", "Topic")
                        .WithMany("Ideas")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.IdeaVotesEntity", b =>
                {
                    b.HasOne("CisApi.Infrastructure.MySQL.Entities.IdeaEntity", "Idea")
                        .WithMany("Votes")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CisApi.Infrastructure.MySQL.Entities.UserEntity", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.TopicEntity", b =>
                {
                    b.HasOne("CisApi.Infrastructure.MySQL.Entities.UserEntity", "CreatedBy")
                        .WithMany("TopicsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.IdeaEntity", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.TopicEntity", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("CisApi.Infrastructure.MySQL.Entities.UserEntity", b =>
                {
                    b.Navigation("IdeasCreated");

                    b.Navigation("TopicsCreated");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
