package jalau.usersapi.infrastructure.mysql;

import jalau.usersapi.core.domain.entities.User;
import jalau.usersapi.core.domain.repositories.IUserRepository;
import jalau.usersapi.infrastructure.mysql.entities.DbUser;
import jalau.usersapi.infrastructure.mysql.mappers.DbUserToUser;
import jalau.usersapi.infrastructure.mysql.mappers.UserToDbUser;
import org.springframework.beans.factory.annotation.Qualifier;

import java.util.List;
import java.util.stream.Collectors;

import jalau.usersapi.infrastructure.mysql.mappers.UserToDbUser;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import jalau.usersapi.infrastructure.mysql.mappers.UserToDbUser;
import org.springframework.stereotype.Repository;
import org.springframework.context.annotation.Profile;


@Repository("mysqlUserRepository")
@Profile({"mysql", "migration"})
class UserRepository implements IUserRepository {
    private final SpringDataUserRepository springDataUserRepository;
    private final DbUserToUser dbUserToUser;
    private final UserToDbUser userToDbUser;

    public UserRepository(SpringDataUserRepository springDataUserRepository, 
                          @Qualifier("mysqlDbUserToUser") DbUserToUser dbUserToUser,
                          @Qualifier("mysqlUserToDbUser") UserToDbUser userToDbUser) {
        this.springDataUserRepository = springDataUserRepository;
        this.dbUserToUser = dbUserToUser;
        this.userToDbUser = userToDbUser;

    }

    /**
     * @param user (Object)
     * @return User Object
     */
    @Override
    public User createUser(User user) {
        // Maps the domain 'User' to the database 'DbUser'.
        DbUser dbUser = userToDbUser.toStructure(user);

        // Saves the entity. The ID is generated by the database.
        DbUser savedDbUser = springDataUserRepository.save(dbUser);

        // Maps the saved entity back to the domain entity with the new ID.
        return dbUserToUser.toDomain(savedDbUser);    }

    /**
     * @param user (Object)
     * @return User Object
     */
    @Override
    public User updateUser(final User user) {
        if (!springDataUserRepository.existsById(user.getId())) {
            return null;
        }

        DbUser userBase = springDataUserRepository.findById(user.getId()).get(); 
        User updatedUser = applyUpdates(user, dbUserToUser.toDomain(userBase));

        DbUser dbUserToUpdate = userToDbUser.toStructure(updatedUser);
        DbUser updatedDbUser = springDataUserRepository.save(dbUserToUpdate);

        return dbUserToUser.toDomain(updatedDbUser);
    }

    private User applyUpdates(final User newUser, final User user) {
        if (newUser.getName() != null) {
            user.setName(newUser.getName());
        }
        if (newUser.getLogin() != null) {
            user.setLogin(newUser.getLogin());
        }
        if (newUser.getPassword() != null) {
            user.setPassword(newUser.getPassword());
        }
        return user;
    }

    /**
     * @param id (String)
     */
    @Override
    public void deleteUser(String id) {
        if (!springDataUserRepository.existsById(id)){
            throw new UsernameNotFoundException(id + " not found");
        }
        springDataUserRepository.deleteById(id);

    }

    /**
     * @return List of Users Objects
     */
    @Override
    public List<User> getUsers() {
        List<DbUser> dbUsers = springDataUserRepository.findAll();
        
        System.out.println(dbUsers);
        
        return dbUsers.stream()
                .map(dbUserToUser::toDomain)
                .collect(Collectors.toList());
    }

    /**
     * @param id (String)
     * @return User Object
     */
    @Override
    public User getUser(String id) {
        User user = springDataUserRepository.findById(id)
                .map(dbUserToUser::toDomain)
                .orElse(null);

        System.out.println(user);

        return user;
    }

    @Override
    public User getUserByLogin(String login) {
        return springDataUserRepository.findByLogin(login)
                .map(dbUserToUser::toDomain)
                .orElse(null);
    }
    
    // all methods throw NotImplemented exception
}
